name: build

on:
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        OCCUPY_SECRET: ${{ secrets.OCCUPY_SECRET }}
        OCCUPY_SECRET_DIR: src/main/resources
        OCCUPY_SECRET_DIR_FILE_NAME: secret.yml
      run: |
        echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME
        ./gradlew build
