name: CD

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Copy secret
        env:
          OCCUPY_SECRET: ${{ secrets.OCCUPY_SECRET }}
          OCCUPY_SECRET_DIR: src/main/resources
          OCCUPY_SECRET_DIR_FILE_NAME: secret.yml
        run: echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deliver File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCCUPY_SSH_HOST }}
          username: ${{ secrets.OCCUPY_SSH_USERNAME }}
          key: ${{ secrets.OCCUPY_SSH_KEY }}
          port: ${{ secrets.OCCUPY_SSH_PORT }}
          source: "build/libs/*.jar"
          target: "source"
          rm: true

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCCUPY_SSH_HOST }}
          username: ${{ secrets.OCCUPY_SSH_USERNAME }}
          key: ${{ secrets.OCCUPY_SSH_KEY }}
          port: ${{ secrets.OCCUPY_SSH_PORT }}
          script: |
            SOURCE_DIR=source/build/libs
            FILE_NAME=`find $SOURCE_DIR/*.jar -printf "%f\n"`
            PID=`ps -ef | grep occupying | grep sudo | grep -v "bash -c" | awk '{print $2}'`

            if [ -z "$PID" ]; then
                    echo "#### THERE IS NO PROCESS ####"
            else
                    echo "#### KILL $PID ####"
                    sudo kill $PID
            fi

            echo "#### RUN $SOURCE_DIR/$FILE_NAME ####"


            sudo java -jar $SOURCE_DIR/$FILE_NAME > /dev/null 2>&1 &
\
